# Netflix Movie Recommendation

## Problem Statement:

* Predict Movies watched together, by most of the Users of Netflix.

### Instances of the dataset:

* list of movies watched together

## Solution:

* The prediction can be made using Association Rule Based Mining.

* Some of the availble Association Rule algorithms are: 

    1. Apriori

    2. Eclat

    3. Frquency Prioroty Growth

## Importing libraries

In [3]:
#data handling libraries
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [4]:
#machine learning libraries
from pyECLAT import ECLAT

## Importing dataset

In [5]:
dataset = pd.read_csv('Netflix Movie Watch Data.csv',header=None)

In [6]:
dataset

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,The Lord of the rings,Cinema Paradiso,Se7en,Avengers: Infinity War,The Shining,High and Low,Terminator 2: Judgment Day,Toy Story,City of God,Witness for the Prosecution,12 Angry Men,Whiplash,Black Panther,Hamilton,The Dark Knight,Once Upon a Time in the West,The Great Dictator,Back to the Future,Aliens,Comedy nights with Kapil
1,The Shawshank Redemption,Fight Club,Pulp Fiction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,The Godfather,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,The Godfather: Part II,Se7en,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,The Dark Knight,The Intouchables,One Flew Over the Cuckoo's Nest,whole wheat Star Wars: Episode V - The Empire ...,Whiplash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7461,Modern Times,psycho,Braveheart,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7462,The Shawshank Redemption,Billa,Pulp Fiction,The Lord of the Rings: The Return of the King,Django Unchained,Whiplash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7463,Prision Break,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7464,Harry Potter 2,Whiplash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7465,Pulp Fiction,Back to the Future,Star Wars: Episode IV - A New Hope,12 Angry Men,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Creating List of Transactions

In [7]:
movies_watched_together = []

for i in range(7466):
    movies_watched_together.append([str(dataset.values[i,j]) for j in range(20)])

## Building & Training Model

In [9]:
eclat = ECLAT(data=dataset,verbose=True)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 118/118 [00:00<00:00, 138.55it/s]
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 118/118 [00:00<00:00, 5671.75it/s]
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 118/118 [00:00<00:00, 4324.25it/s]

## Rules Formed

## Formulas

1. Support(B) = (Transactions containing (B))/(Total Transactions)

### Using Eclat

In [10]:
from apyori import apriori

In [11]:
rules = apriori(transactions=movies_watched_together,min_support=0.003,min_confidence=0.5,min_lift=3, min_length=2,max_length=3)

In [12]:
results = list(rules)

In [13]:
results

[RelationRecord(items=frozenset({'Billa', 'The Intouchables', "Schindler's List"}), support=0.004018215912135012, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Billa', "Schindler's List"}), items_add=frozenset({'The Intouchables'}), confidence=0.5, lift=3.8524251805985554)]),
 RelationRecord(items=frozenset({'Prision Break', 'The Intouchables', 'Comedy nights with Kapil'}), support=0.003616394320921511, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Prision Break', 'Comedy nights with Kapil'}), items_add=frozenset({'The Intouchables'}), confidence=0.5, lift=3.8524251805985554)]),
 RelationRecord(items=frozenset({'The Lion King', 'The Lord of the Rings: The Fellowship of the Ring', 'Comedy nights with Kapil'}), support=0.004420037503348513, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Lion King', 'Comedy nights with Kapil'}), items_add=frozenset({'The Lord of the Rings: The Fellowship of the Ring'}), confidence=0.611111111111111, lift=3.496211153682418)]),
 RelationRecord(items=frozenset({'inception', 'Once Upon a Time in America', 'The Lord of the Rings: The Fellowship of the Ring'}), support=0.0030806321993035093, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Once Upon a Time in America', 'inception'}), items_add=frozenset({'The Lord of the Rings: The Fellowship of the Ring'}), confidence=0.6764705882352942, lift=3.870137480279469)]),
 RelationRecord(items=frozenset({'Pulp Fiction', 'The Lord of the Rings: The Two Towers', 'The Lord of the Rings: The Fellowship of the Ring'}), support=0.003750334851326011, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Pulp Fiction', 'The Lord of the Rings: The Two Towers'}), items_add=frozenset({'The Lord of the Rings: The Fellowship of the Ring'}), confidence=0.5283018867924528, lift=3.022453553097665)]),
 RelationRecord(items=frozenset({'inception', 'The Departed', 'The Lord of the Rings: The Fellowship of the Ring'}), support=0.004821859094562015, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Departed', 'inception'}), items_add=frozenset({'The Lord of the Rings: The Fellowship of the Ring'}), confidence=0.5714285714285714, lift=3.269184455391352)]),
 RelationRecord(items=frozenset({'inception', 'The Wolf of Wall Street', 'The Lord of the Rings: The Fellowship of the Ring'}), support=0.0030806321993035093, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Wolf of Wall Street', 'inception'}), items_add=frozenset({'The Lord of the Rings: The Fellowship of the Ring'}), confidence=0.5750000000000001, lift=3.2896168582375487)])]

In [15]:
tuple(results[0][2][0][0])[0]

'Billa'

In [16]:
tuple(results[0][2][0][1])[0]

'The Intouchables'

## Data Frame of results obtained

In [17]:
def inspect(results):
    product1 = [tuple(result[2][0][0])[0] for result in results]
    product2 = [tuple(result[2][0][1])[0] for result in results]
    support = [result[1] for result in results]
    return list(zip(product1,product2, support))

In [18]:
DataFrame = pd.DataFrame(inspect(results),columns=['product1','product2','support'])

In [19]:
DataFrame

,product1,product2,support
0,Billa,The Intouchables,0.004018
1,Prision Break,The Intouchables,0.003616
2,The Lion King,The Lord of the Rings: The Fellowship of the Ring,0.004420
3,Once Upon a Time in America,The Lord of the Rings: The Fellowship of the Ring,0.003081
4,Pulp Fiction,The Lord of the Rings: The Fellowship of the Ring,0.003750
5,The Departed,The Lord of the Rings: The Fellowship of the Ring,0.004822
6,The Wolf of Wall Street,The Lord of the Rings: The Fellowship of the Ring,0.003081

## Top 3 associations

In [20]:
DataFrame.nlargest(n=3,columns='support')

        product1                                           product2   support
5   The Departed  The Lord of the Rings: The Fellowship of the Ring  0.004822
2  The Lion King  The Lord of the Rings: The Fellowship of the Ring  0.004420
0          Billa                                   The Intouchables  0.004018